service:
  log_level: warn
  parsers_file: /parser.conf
  # storage.path: /fb-storage
  # storage.sync: normal
  # storage.total_limit_size: 1G
  # storage.backlog.mem_limit: 128M

pipeline:
  inputs:
  - name: tail
    tag: app.feeder
    path: /logs/feeder.json
    read_from_head: yes
    mem_buf_limit: 64M
    parser: feeder
    processors:
      logs:
      - name: modify
        add: service feeder
  - name: tail
    tag: app.statistics
    path: /logs/statistics.json
    read_from_head: yes
    mem_buf_limit: 64M
    exit_on_eof: yes
    parser: statistics
    processors:
      logs:
      - name: modify
        add: service statistics
  - name: tail
    tag: app.storage
    path: /logs/storage.json
    read_from_head: yes
    mem_buf_limit: 64M
    parser: storage
    processors:
      logs:
      - name: modify
        add: service storage
  outputs:
  - name: es
    match: app.*
    host: es01
    port: 9200
    compress: gzip
    suppress_type_name: on
    http_user: elastic
    http_passwd: changeme
    logstash_format: yes
    buffer_size: 16M
    # pipeline: 
    tls: on
    tls.ca_file: /ca/ca/ca.crt


