service:
  log_level: warn
  parsers_file: /parser.conf
  # storage.path: /fb-storage
  # storage.sync: normal
  # storage.total_limit_size: 1G
  # storage.backlog.mem_limit: 128M

pipeline:
  inputs:
  - name: tail
    tag: app.feeder
    path: /logs/feeder.log
    read_from_head: yes
    mem_buf_limit: 64M
    processors:
      logs:
      - name: modify
        add: service feeder
  - name: tail
    tag: app.statistics
    path: /logs/statistics.log
    read_from_head: yes
    mem_buf_limit: 64M
    exit_on_eof: yes
    processors:
      logs:
      - name: modify
        add: service statistics
  - name: tail
    tag: app.storage
    path: /logs/storage-uwsgi.log
    read_from_head: yes
    mem_buf_limit: 64M
    processors:
      logs:
      - name: modify
        add: service storage
  # filters:
  # - name: multiline
  #   match: app.feeder
  #   multiline.key_content: log
  #   multiline.parser: go
  # - name: multiline
  #   match: app.statistics
  #   multiline.key_content: log
  #   multiline.parser: logback
  # - name: multiline
  #   match: app.storage
  #   multiline.key_content: log
  #   multiline.parser: python
  outputs:
  - name: es
    match: app.*
    host: es01
    port: 9200
    compress: gzip
    suppress_type_name: on
    http_user: elastic
    http_passwd: changeme
    logstash_format: yes
    buffer_size: 16M
    # pipeline: 
    tls: on
    tls.ca_file: /ca/ca/ca.crt


